"""
Central configuration for the face-recognition door access system.
Tune these values without touching the logic in enroll.py / recognize.py.
"""

import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ---- Data locations -------------------------------------------------------
EMPLOYEES_DIR = os.path.join(BASE_DIR, "data", "employees")   # data/employees/<name>/*.jpg|*.mp4
ENCODINGS_FILE = os.path.join(BASE_DIR, "encodings.pkl")      # generated by enroll.py
EMPLOYEES_JSON = os.path.join(BASE_DIR, "employees.json")     # generated/updated by enroll.py
ACCESS_LOG_JSON = os.path.join(BASE_DIR, "access_log.json")   # every open/deny event, appended
ALERTS_DIR = os.path.join(BASE_DIR, "alerts")                 # snapshots of denied attempts

# ---- Enrollment -------------------------------------------------------
# How many frames to sample from each video per person (spread evenly through the clip)
VIDEO_SAMPLE_FRAMES = 15
# Skip a video frame that is too blurry/small to bother encoding
MIN_FACE_SIZE_PX = 40
# Encoding jitters: averages the encoding over N slightly perturbed crops.
# More stable/accurate encodings at enrollment time (one-time cost, so fine
# to keep this higher than you'd use live).
ENROLL_NUM_JITTERS = 5

# Each employee folder may contain this file to control door access, e.g.:
#   authorized: true
# If the file is missing, DEFAULT_AUTHORIZED_IF_MISSING applies. Keeping this
# False means new employee folders are locked out until someone deliberately
# authorizes them -- safer default for a door than accidentally open.
ACCESS_CONFIG_FILENAME = "access.yaml"
DEFAULT_AUTHORIZED_IF_MISSING = False

# ---- Recognition -------------------------------------------------------
# USB webcam: use an integer index, e.g. 0
# IP/network camera: use the stream URL as a string, e.g.:
#   "http://192.168.1.35:81/stream"   (common for ESP32-CAM style modules)
#   "rtsp://192.168.1.35:554/stream1" (common for RTSP-capable IP cams)
# If your camera has a login, embed it: "http://user:pass@192.168.1.35:81/stream"
CAMERA_SOURCE = "http://192.168.1.35:81/stream"
FRAME_RESIZE_SCALE = 0.5    # downscale frames for speed (1.0 = full res)
PROCESS_EVERY_N_FRAMES = 3  # only run detection every Nth frame to save CPU

# Lower = stricter match. With only one person enrolled, false-accepts of
# strangers are much likelier than false-rejects of you, so bias strict.
# Start at 0.45; if you personally still get rejected sometimes, raise in
# steps of 0.02. If strangers still get in, lower in steps of 0.02.
MATCH_TOLERANCE = 0.45

# Require this many consecutive processed frames to match the SAME person
# before granting access. Kills one-off misfires from a bad angle/lighting
# on a single frame. 3-5 is a good range; higher = slower to open but safer.
CONSECUTIVE_MATCHES_REQUIRED = 4

# If more than this many faces are detected in frame at once, the door never
# opens (anti-tailgating / anti-piggybacking), even if one of them is you.
MAX_FACES_ALLOWED = 1

# Seconds to wait before re-logging/re-alerting the same person, to avoid spam
COOLDOWN_SECONDS = 8

# How long (seconds) the door stays "open" per successful match
DOOR_OPEN_SECONDS = 4

# ---- Alerts -------------------------------------------------------
# Set to True and fill in SMTP details in alerts.py if you want emailed warnings.
ENABLE_EMAIL_ALERTS = False
SMTP_HOST = "smtp.example.com"
SMTP_PORT = 587
SMTP_USER = "alerts@example.com"
SMTP_PASSWORD = "changeme"
ALERT_RECIPIENTS = ["security@example.com"]
